defmodule Mix.Tasks.Devcontainers.Init do
  @moduledoc """
  Generates a Docker Compose file with selected services.

  ## Usage

      mix devcontainers.init [options]

  ## Options

    * `--postgres` - Include PostgreSQL service
    * `--mysql` - Include MySQL service
    * `--redis` - Include Redis service
    * `--rabbitmq` - Include RabbitMQ service
    * `--kafka` - Include Kafka service
    * `--mongodb` - Include MongoDB service
    * `--elasticsearch` - Include Elasticsearch service
    * `--all` - Include all services
    * `--file` - Output file name (default: compose.yml)
    * `--force` - Overwrite existing file

  ## Examples

      # Create compose.yml with PostgreSQL and Redis
      mix devcontainers.init --postgres --redis

      # Create compose.yml with all services
      mix devcontainers.init --all

      # Create with custom filename
      mix devcontainers.init --postgres --file docker-compose.dev.yml

  """
  @shortdoc "Generates a Docker Compose file"

  use Mix.Task

  @switches [
    postgres: :boolean,
    mysql: :boolean,
    redis: :boolean,
    rabbitmq: :boolean,
    kafka: :boolean,
    mongodb: :boolean,
    elasticsearch: :boolean,
    all: :boolean,
    file: :string,
    force: :boolean
  ]

  @impl Mix.Task
  def run(args) do
    {opts, _, _} = OptionParser.parse(args, switches: @switches)

    file = Keyword.get(opts, :file, "compose.yml")
    force = Keyword.get(opts, :force, false)

    if File.exists?(file) and not force do
      Mix.shell().error("File #{file} already exists. Use --force to overwrite.")
      exit({:shutdown, 1})
    end

    services = selected_services(opts)

    if Enum.empty?(services) do
      Mix.shell().info("""
      No services selected. Use one or more of:
        --postgres, --mysql, --redis, --rabbitmq, --kafka, --mongodb, --elasticsearch, --all
      """)

      exit({:shutdown, 1})
    end

    content = generate_compose(services)
    File.write!(file, content)

    Mix.shell().info("Created #{file} with services: #{Enum.join(services, ", ")}")
    Mix.shell().info("")
    Mix.shell().info("Next steps:")
    Mix.shell().info("  1. Review and customize #{file}")
    Mix.shell().info("  2. Run `mix devcontainers.up` to start services")
    Mix.shell().info("  3. Or just run your app - services start automatically!")
  end

  defp selected_services(opts) do
    if Keyword.get(opts, :all) do
      [:postgres, :mysql, :redis, :rabbitmq, :kafka, :mongodb, :elasticsearch]
    else
      [:postgres, :mysql, :redis, :rabbitmq, :kafka, :mongodb, :elasticsearch]
      |> Enum.filter(&Keyword.get(opts, &1, false))
    end
  end

  defp generate_compose(services) do
    services_yaml =
      services
      |> Enum.map(&service_template/1)
      |> Enum.join("\n")

    """
    # Generated by mix devcontainers.init
    # See https://docs.docker.com/compose/compose-file/ for full reference

    services:
    #{services_yaml}
    """
  end

  defp service_template(:postgres) do
    """
      db:
        image: postgres:15
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: #{app_name()}_dev
        ports:
          - "5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data

    volumes:
      postgres_data:
    """
  end

  defp service_template(:mysql) do
    """
      db:
        image: mysql:8
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: #{app_name()}
          MYSQL_PASSWORD: secret
          MYSQL_DATABASE: #{app_name()}_dev
        ports:
          - "3306"
        volumes:
          - mysql_data:/var/lib/mysql

    volumes:
      mysql_data:
    """
  end

  defp service_template(:redis) do
    """
      redis:
        image: redis:7-alpine
        ports:
          - "6379"
        volumes:
          - redis_data:/data

    volumes:
      redis_data:
    """
  end

  defp service_template(:rabbitmq) do
    """
      rabbitmq:
        image: rabbitmq:3-management
        environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - "5672"
          - "15672"
        volumes:
          - rabbitmq_data:/var/lib/rabbitmq

    volumes:
      rabbitmq_data:
    """
  end

  defp service_template(:kafka) do
    """
      kafka:
        image: bitnami/kafka:3.6
        environment:
          KAFKA_CFG_NODE_ID: 0
          KAFKA_CFG_PROCESS_ROLES: controller,broker
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
        ports:
          - "9092"
        volumes:
          - kafka_data:/bitnami/kafka

    volumes:
      kafka_data:
    """
  end

  defp service_template(:mongodb) do
    """
      mongo:
        image: mongo:7
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: secret
          MONGO_INITDB_DATABASE: #{app_name()}_dev
        ports:
          - "27017"
        volumes:
          - mongo_data:/data/db

    volumes:
      mongo_data:
    """
  end

  defp service_template(:elasticsearch) do
    """
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        environment:
          discovery.type: single-node
          xpack.security.enabled: "false"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        ports:
          - "9200"
        volumes:
          - elasticsearch_data:/usr/share/elasticsearch/data

    volumes:
      elasticsearch_data:
    """
  end

  defp app_name do
    Mix.Project.config()[:app] |> to_string()
  end
end
